import DOMPurify from "dompurify";

export function sanitizeEveryBookHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "p",
      "span",
      "strong",
      "em",
      "section",
      "article",
      "div",
      "img",
      "audio",
      "video",
      "button",
      "ul",
      "ol",
      "li",
      "br",
      "blockquote",
      "hr",
    ],
    ALLOWED_ATTR: [
      "src",
      "alt",
      "controls",
      "class",
      "id",
      "title",

      // EveryBook runtime actions
      "data-ebk-action",
      "data-target",
      "data-chapter-id",
      "data-page-id",
      "data-choice-id",
      "data-key",
      "data-value",
      "data-ebk-if",
    ],
    FORBID_TAGS: [
      "script",
      "iframe",
      "object",
      "embed",
      "form",
      "input",
      "textarea",
      "select",
      "link",
      "meta",
      "base",
    ],
    FORBID_ATTR: [
      "onclick",
      "onload",
      "onerror",
      "onmouseover",
      "onfocus",
      "onblur",
      "style",
    ],
    ALLOW_DATA_ATTR: true,
  });
}